// <auto-generated />
using System;
using AirCompany.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirCompany.Infrastructure.Migrations
{
    [DbContext(typeof(AirCompanyDbContext))]
    [Migration("20251108181521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AirCompany.Domain.Models.AircraftFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("aircraft_families");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Airbus",
                            Name = "Family-1"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Boeing",
                            Name = "Family-2"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Embraer",
                            Name = "Family-3"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Bombardier",
                            Name = "Family-4"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Airbus",
                            Name = "Family-5"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Airbus",
                            Name = "Family-6"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "Boeing",
                            Name = "Family-7"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "Boeing",
                            Name = "Family-8"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Embraer",
                            Name = "Family-9"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "Airbus",
                            Name = "Family-10"
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Models.AircraftModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftFamilyId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_family_id");

                    b.Property<double>("CargoCapacity")
                        .HasColumnType("double")
                        .HasColumnName("cargo_capacity");

                    b.Property<double>("FlightRange")
                        .HasColumnType("double")
                        .HasColumnName("flight_range");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int")
                        .HasColumnName("passenger_capacity");

                    b.HasKey("Id");

                    b.HasIndex("AircraftFamilyId");

                    b.ToTable("aircraft_models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftFamilyId = 1,
                            CargoCapacity = 5000.0,
                            FlightRange = 6100.0,
                            Name = "A320-200",
                            PassengerCapacity = 180
                        },
                        new
                        {
                            Id = 2,
                            AircraftFamilyId = 2,
                            CargoCapacity = 4800.0,
                            FlightRange = 5600.0,
                            Name = "B737-800",
                            PassengerCapacity = 160
                        },
                        new
                        {
                            Id = 3,
                            AircraftFamilyId = 3,
                            CargoCapacity = 2500.0,
                            FlightRange = 4500.0,
                            Name = "E190",
                            PassengerCapacity = 100
                        },
                        new
                        {
                            Id = 4,
                            AircraftFamilyId = 4,
                            CargoCapacity = 2000.0,
                            FlightRange = 3700.0,
                            Name = "CRJ900",
                            PassengerCapacity = 90
                        },
                        new
                        {
                            Id = 5,
                            AircraftFamilyId = 5,
                            CargoCapacity = 12000.0,
                            FlightRange = 11000.0,
                            Name = "A330-300",
                            PassengerCapacity = 300
                        },
                        new
                        {
                            Id = 6,
                            AircraftFamilyId = 6,
                            CargoCapacity = 5200.0,
                            FlightRange = 7400.0,
                            Name = "A321neo",
                            PassengerCapacity = 200
                        },
                        new
                        {
                            Id = 7,
                            AircraftFamilyId = 7,
                            CargoCapacity = 14000.0,
                            FlightRange = 13620.0,
                            Name = "B787-8",
                            PassengerCapacity = 242
                        },
                        new
                        {
                            Id = 8,
                            AircraftFamilyId = 8,
                            CargoCapacity = 4900.0,
                            FlightRange = 5800.0,
                            Name = "B737-900",
                            PassengerCapacity = 175
                        },
                        new
                        {
                            Id = 9,
                            AircraftFamilyId = 9,
                            CargoCapacity = 2600.0,
                            FlightRange = 4800.0,
                            Name = "E195-E2",
                            PassengerCapacity = 120
                        },
                        new
                        {
                            Id = 10,
                            AircraftFamilyId = 10,
                            CargoCapacity = 15000.0,
                            FlightRange = 15000.0,
                            Name = "A350-900",
                            PassengerCapacity = 320
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftModelId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_model_id");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arrival_airport");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrival_datetime");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("departure_airport");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departure_datetime");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time(6)")
                        .HasColumnName("duration");

                    b.HasKey("Id");

                    b.HasIndex("AircraftModelId");

                    b.ToTable("flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftModelId = 1,
                            ArrivalAirport = "London",
                            ArrivalDate = new DateTime(2025, 10, 24, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU101",
                            DepartureAirport = "Moscow",
                            DepartureDate = new DateTime(2025, 10, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 2, 30, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            AircraftModelId = 2,
                            ArrivalAirport = "Paris",
                            ArrivalDate = new DateTime(2025, 10, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU102",
                            DepartureAirport = "Moscow",
                            DepartureDate = new DateTime(2025, 10, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AircraftModelId = 3,
                            ArrivalAirport = "Berlin",
                            ArrivalDate = new DateTime(2025, 10, 26, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU103",
                            DepartureAirport = "Saint Petersburg",
                            DepartureDate = new DateTime(2025, 10, 26, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            AircraftModelId = 5,
                            ArrivalAirport = "New York",
                            ArrivalDate = new DateTime(2025, 10, 27, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU104",
                            DepartureAirport = "Moscow",
                            DepartureDate = new DateTime(2025, 10, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            AircraftModelId = 5,
                            ArrivalAirport = "Tokyo",
                            ArrivalDate = new DateTime(2025, 10, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU105",
                            DepartureAirport = "Moscow",
                            DepartureDate = new DateTime(2025, 10, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            AircraftModelId = 4,
                            ArrivalAirport = "Paris",
                            ArrivalDate = new DateTime(2025, 10, 24, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU106",
                            DepartureAirport = "Berlin",
                            DepartureDate = new DateTime(2025, 10, 24, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            AircraftModelId = 2,
                            ArrivalAirport = "Dubai",
                            ArrivalDate = new DateTime(2025, 10, 29, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU107",
                            DepartureAirport = "Moscow",
                            DepartureDate = new DateTime(2025, 10, 29, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            AircraftModelId = 1,
                            ArrivalAirport = "London",
                            ArrivalDate = new DateTime(2025, 10, 30, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU108",
                            DepartureAirport = "Saint Petersburg",
                            DepartureDate = new DateTime(2025, 10, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            AircraftModelId = 3,
                            ArrivalAirport = "Berlin",
                            ArrivalDate = new DateTime(2025, 10, 31, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU109",
                            DepartureAirport = "Moscow",
                            DepartureDate = new DateTime(2025, 10, 31, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            AircraftModelId = 10,
                            ArrivalAirport = "Moscow",
                            ArrivalDate = new DateTime(2025, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Code = "SU110",
                            DepartureAirport = "Paris",
                            DepartureDate = new DateTime(2025, 11, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 3, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("passport_number");

                    b.HasKey("Id");

                    b.ToTable("passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1985, 1, 10),
                            FullName = "Ivanov Ivan Ivanovich",
                            PassportNumber = "P000001"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1990, 2, 20),
                            FullName = "Petrov Petr Petrovich",
                            PassportNumber = "P000002"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1988, 3, 15),
                            FullName = "Sidorov Sidor Sidorovich",
                            PassportNumber = "P000003"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1992, 4, 5),
                            FullName = "Kuznetsov Alexey Alexeevich",
                            PassportNumber = "P000004"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1995, 5, 25),
                            FullName = "Smirnova Anna Sergeevna",
                            PassportNumber = "P000005"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1987, 6, 18),
                            FullName = "Volkov Dmitry Ivanovich",
                            PassportNumber = "P000006"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1991, 7, 30),
                            FullName = "Lebedev Sergey Nikolaevich",
                            PassportNumber = "P000007"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1993, 8, 12),
                            FullName = "Morozova Elena Vladimirovna",
                            PassportNumber = "P000008"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1989, 9, 9),
                            FullName = "Nikolaev Nikolay Ivanovich",
                            PassportNumber = "P000009"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1994, 10, 2),
                            FullName = "Fedorova Olga Petrovna",
                            PassportNumber = "P000010"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1984, 11, 11),
                            FullName = "Orlov Maxim Viktorovich",
                            PassportNumber = "P000011"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(1996, 12, 12),
                            FullName = "Sorokina Marina Igorevna",
                            PassportNumber = "P000012"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(1986, 6, 6),
                            FullName = "Gusev Roman Dmitrievich",
                            PassportNumber = "P000013"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(1992, 9, 1),
                            FullName = "Markova Irina Sergeevna",
                            PassportNumber = "P000014"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(1983, 3, 3),
                            FullName = "Nikiforov Alexey Pavlovich",
                            PassportNumber = "P000015"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateOnly(1990, 4, 4),
                            FullName = "Belov Dmitry Sergeevich",
                            PassportNumber = "P000016"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateOnly(1988, 8, 8),
                            FullName = "Karpova Olga Ivanovna",
                            PassportNumber = "P000017"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateOnly(1991, 1, 1),
                            FullName = "Rozov Pavel Anatolievich",
                            PassportNumber = "P000018"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateOnly(1997, 7, 7),
                            FullName = "Simonova Vera Nikolaevna",
                            PassportNumber = "P000019"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateOnly(1982, 2, 2),
                            FullName = "Antonov Ilya Sergeevich",
                            PassportNumber = "P000020"
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BaggageWeight")
                        .HasColumnType("double")
                        .HasColumnName("baggage_weight");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<bool?>("HasHandLuggage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_hand_luggage");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("seat_number");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaggageWeight = 0.0,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 1,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 2,
                            BaggageWeight = 12.0,
                            FlightId = 1,
                            HasHandLuggage = false,
                            PassengerId = 2,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 3,
                            BaggageWeight = 8.0,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 3,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 4,
                            BaggageWeight = 0.0,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 4,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 5,
                            BaggageWeight = 15.0,
                            FlightId = 1,
                            HasHandLuggage = false,
                            PassengerId = 5,
                            SeatNumber = "1E"
                        },
                        new
                        {
                            Id = 6,
                            BaggageWeight = 10.0,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 6,
                            SeatNumber = "1F"
                        },
                        new
                        {
                            Id = 7,
                            BaggageWeight = 0.0,
                            FlightId = 1,
                            HasHandLuggage = false,
                            PassengerId = 7,
                            SeatNumber = "1G"
                        },
                        new
                        {
                            Id = 8,
                            BaggageWeight = 9.0,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 8,
                            SeatNumber = "1H"
                        },
                        new
                        {
                            Id = 9,
                            BaggageWeight = 0.0,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 9,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 10,
                            BaggageWeight = 11.0,
                            FlightId = 2,
                            HasHandLuggage = false,
                            PassengerId = 10,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 11,
                            BaggageWeight = 7.0,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 11,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 12,
                            BaggageWeight = 0.0,
                            FlightId = 2,
                            HasHandLuggage = false,
                            PassengerId = 12,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 13,
                            BaggageWeight = 14.0,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 13,
                            SeatNumber = "2E"
                        },
                        new
                        {
                            Id = 14,
                            BaggageWeight = 6.0,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 14,
                            SeatNumber = "2F"
                        },
                        new
                        {
                            Id = 15,
                            BaggageWeight = 0.0,
                            FlightId = 2,
                            HasHandLuggage = false,
                            PassengerId = 15,
                            SeatNumber = "2G"
                        },
                        new
                        {
                            Id = 16,
                            BaggageWeight = 5.0,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 16,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 17,
                            BaggageWeight = 0.0,
                            FlightId = 3,
                            HasHandLuggage = false,
                            PassengerId = 17,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 18,
                            BaggageWeight = 13.0,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 18,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 19,
                            BaggageWeight = 0.0,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 19,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 20,
                            BaggageWeight = 8.0,
                            FlightId = 3,
                            HasHandLuggage = false,
                            PassengerId = 20,
                            SeatNumber = "3E"
                        },
                        new
                        {
                            Id = 21,
                            BaggageWeight = 10.0,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 1,
                            SeatNumber = "3F"
                        },
                        new
                        {
                            Id = 22,
                            BaggageWeight = 0.0,
                            FlightId = 4,
                            HasHandLuggage = true,
                            PassengerId = 2,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 23,
                            BaggageWeight = 20.0,
                            FlightId = 4,
                            HasHandLuggage = false,
                            PassengerId = 3,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 24,
                            BaggageWeight = 7.0,
                            FlightId = 4,
                            HasHandLuggage = true,
                            PassengerId = 4,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 25,
                            BaggageWeight = 0.0,
                            FlightId = 4,
                            HasHandLuggage = false,
                            PassengerId = 5,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 26,
                            BaggageWeight = 18.0,
                            FlightId = 4,
                            HasHandLuggage = true,
                            PassengerId = 6,
                            SeatNumber = "4E"
                        },
                        new
                        {
                            Id = 27,
                            BaggageWeight = 0.0,
                            FlightId = 5,
                            HasHandLuggage = false,
                            PassengerId = 7,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 28,
                            BaggageWeight = 9.0,
                            FlightId = 5,
                            HasHandLuggage = true,
                            PassengerId = 8,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 29,
                            BaggageWeight = 12.0,
                            FlightId = 5,
                            HasHandLuggage = true,
                            PassengerId = 9,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 30,
                            BaggageWeight = 6.0,
                            FlightId = 5,
                            HasHandLuggage = false,
                            PassengerId = 10,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 31,
                            BaggageWeight = 0.0,
                            FlightId = 6,
                            HasHandLuggage = true,
                            PassengerId = 11,
                            SeatNumber = "6A"
                        },
                        new
                        {
                            Id = 32,
                            BaggageWeight = 11.0,
                            FlightId = 6,
                            HasHandLuggage = false,
                            PassengerId = 12,
                            SeatNumber = "6B"
                        },
                        new
                        {
                            Id = 33,
                            BaggageWeight = 14.0,
                            FlightId = 6,
                            HasHandLuggage = true,
                            PassengerId = 13,
                            SeatNumber = "6C"
                        },
                        new
                        {
                            Id = 34,
                            BaggageWeight = 0.0,
                            FlightId = 7,
                            HasHandLuggage = false,
                            PassengerId = 14,
                            SeatNumber = "7A"
                        },
                        new
                        {
                            Id = 35,
                            BaggageWeight = 10.0,
                            FlightId = 7,
                            HasHandLuggage = true,
                            PassengerId = 15,
                            SeatNumber = "7B"
                        },
                        new
                        {
                            Id = 36,
                            BaggageWeight = 7.0,
                            FlightId = 8,
                            HasHandLuggage = true,
                            PassengerId = 16,
                            SeatNumber = "8A"
                        },
                        new
                        {
                            Id = 37,
                            BaggageWeight = 0.0,
                            FlightId = 8,
                            HasHandLuggage = false,
                            PassengerId = 17,
                            SeatNumber = "8B"
                        },
                        new
                        {
                            Id = 38,
                            BaggageWeight = 8.0,
                            FlightId = 9,
                            HasHandLuggage = true,
                            PassengerId = 18,
                            SeatNumber = "9A"
                        },
                        new
                        {
                            Id = 39,
                            BaggageWeight = 0.0,
                            FlightId = 9,
                            HasHandLuggage = false,
                            PassengerId = 19,
                            SeatNumber = "9B"
                        },
                        new
                        {
                            Id = 40,
                            BaggageWeight = 16.0,
                            FlightId = 10,
                            HasHandLuggage = true,
                            PassengerId = 20,
                            SeatNumber = "10A"
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Models.AircraftModel", b =>
                {
                    b.HasOne("AirCompany.Domain.Models.AircraftFamily", "AircraftFamily")
                        .WithMany("Models")
                        .HasForeignKey("AircraftFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftFamily");
                });

            modelBuilder.Entity("AirCompany.Domain.Models.Flight", b =>
                {
                    b.HasOne("AirCompany.Domain.Models.AircraftModel", "AircraftModel")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftModel");
                });

            modelBuilder.Entity("AirCompany.Domain.Models.Ticket", b =>
                {
                    b.HasOne("AirCompany.Domain.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirCompany.Domain.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AirCompany.Domain.Models.AircraftFamily", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AirCompany.Domain.Models.AircraftModel", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirCompany.Domain.Models.Flight", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AirCompany.Domain.Models.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
